FROM alpine:3.22.0

RUN apk add --no-cache \
    bash               \
    cmake              \
    git                \
    gdb                \
    gcc-arm-none-eabi

WORKDIR /workspace

CMD [ "bash" ]